### ISSUE TITLE
About DecoderCallback cannot found error

### ISSUE THREAD

**Issue by CaiJingLong** [fluttercandies/flutter_photo_manager#1021]
This API has been officially removed by flutter. I plan to release version 3.0 in the future and remove the related API, and release an independent package to inherit flutter's ImageProvider.
Until then, I recommended use stable of flutter SDK first.

**Comment by CaiJingLong** [comment]
Use 3.0.0-dev.1 first.
---
If it is not any other reports next week, I will push the release version instead of the dev version.

**Comment by imdtushar** [comment]
../../.pub-cache/hosted/pub.dev/photo_manager-2.7.2/lib/src/internal/image_provider.dart:71:5: Error: Type 'DecoderCallback' not found.
    DecoderCallback decode, // ignore: deprecated_member_use
    
    
    still issue with latest Version

**Comment by Ben1980** [comment]
Upgraded Flutter today to stable 3.16 and got the same error. When is photo_manager getting to stable 3.0.0?

**Comment by xacaciax** [comment]
Same issue here

**Comment by den0206** [comment]
@Ben1980 @xacaciax 

Temporary fix.

``` yaml
// if you use
dependencies:
  wechat_assets_picker: ^8.9.0-dev.1

dependency_overrides: 
  photo_manager: ^3.0.0-dev.2

```

I'm waiting for it to be updated to stable version :)
