### ISSUE TITLE
[BUG] originFile does not return the edited image

### ISSUE THREAD

**Issue by vishnukvmd** [fluttercandies/flutter_photo_manager#636]
**Describe the bug**
If you edit an image from the iOS photos app, and call `asset.originFile`, the returned file does not contain the edits. On the other hand, `asset.file` returns the edited file as expected.

**To Reproduce**
1. Open a file in iOS Photos app
2. Reduce the saturation to a minimum, converting the image to black and white
3. Now return to your app and open the file using `asset.originFile`
4. The returned file will be the original, unedited file

**Expected behavior**
`asset.originFile` should behave similarly to `asset.file` and return the edited file.

**Flutter version**: 2.5.2

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro
 - OS: 15.0.2

**Comment by NaikSoftware** [comment]
Confirm issue, in our project I use this workaround:

```dart
if (kIsAndroid) {
      return asset.file;
    } else if (kIsIOS) {
      // asset.file brakes gif animation on ios
      // asset.originFile discards all editing on ios

      final handler = PMProgressHandler();
      handler.stream.listen((event) {
        Logger.debug(
            'Media',
            'loading $asset => ${event.progress},'
                ' ${event.state} -- ${DateTime.now().millisecondsSinceEpoch}');
      });
      File? file = await asset
          .loadFile(isOrigin: true, progressHandler: handler)
          .timeout(const Duration(seconds: 10));
      if (file != null && !file.isAnimated) {
        file = await asset.file;
      }
      return file;
    }
```

**Comment by Kal-Elx** [comment]
Hi @AlexV525!

I'm on the latest commit a3be8cd605475208a60c607e22674ea3724bb8e8 which has bdba618afceb560def0116d78eea1cd2cfd9b74f that should have solved this but I'm still seeing this issue.
Just as @vishnukvmd I get the edited file when calling `file` but not with `originFile`.

pubspec.yaml
```
photo_manager:
    git:
      url: git://github.com/fluttercandies/flutter_photo_manager.git
      ref: master
```

pubspec.lock
```
photo_manager:
    dependency: "direct main"
    description:
      path: "."
      ref: master
      resolved-ref: a3be8cd605475208a60c607e22674ea3724bb8e8
      url: "git://github.com/fluttercandies/flutter_photo_manager.git"
    source: git
    version: "2.0.0-dev.2"
```
